# =================================================================================================
# General & Window
# =================================================================================================
keep-open=yes
#autofit="1855x1043"
autofit-larger=1855x1043
#save-position-on-quit=yes
# remember ALT + F3 to bring the top bar back!

# =================================================================================================
# Video & Decoding
# =================================================================================================
hwdec=auto
vo=gpu-next
gpu-context=wayland
#scale-antiring=0.6
#profile=high-quality

# =================================================================================================
# Streaming (yt-dlp)
# =================================================================================================
ytdl-format=bestvideo[height<=1080]+bestaudio/best
ytdl-raw-options=cookies-from-browser=firefox

#ytdl-cookies-from-browser=vivaldi
#ytdl-format=bestvideo[height<=?1080][vcodec!=?vp9]+bestaudio/best
#ytdl-format=bestvideo[height<=1080][vcodec^=avc1]+bestaudio/best[height<=1080][ext=mp4]

# =================================================================================================
# Screenshots
# =================================================================================================
screenshot-format=webp
#screenshot-format=png
screenshot-webp-lossless=yes
screenshot-dir="~/Pictures/.mpv-ss/"
screenshot-template="%F %p %n"
#screenshot-high-bit-depth=no
#screenshot-png-compression=0

# =================================================================================================
# Audio & Language
# =================================================================================================
audio-channels=stereo # wow life saved
alang=jpn,ja
slang=eng,en

# =================================================================================================
# Subtitles
# =================================================================================================
sub-ass-override=no
sub-ass-style-overrides=playresx=1920,playresy=1080
#sub-font="Gandhi Sans"
sub-font="Trebuchet MS"
sub-font-size=50
sub-bold=yes
sub-color="#FFFFFF"
sub-back-color="#33000000"
sub-border-size=2.4
sub-border-color="#FF000000"
sub-shadow-color="#A0000000"
sub-shadow-offset=0.75
sub-margin-y=40
sub-scale=0.9
# sub-ass-style-overrides=Kerning=yes

# =================================================================================================
# Conditional Profiles
# =================================================================================================

#[bigvideo]
#autofit=1855x1043
#profile-cond=width >= 1920 and height >= 1080

[crunchyroll]
profile-cond=filename:match("SubsPlease") or filename:match("Erai%-raws") or filename:match("HorribleSubs")
profile-restore=copy
sub-ass-use-video-data=aspect-ratio

[simulcast]
profile-cond=(function(a)for b,c in ipairs(a)do if filename:match(c)then return true end end end)({"SubsPlease","Erai%-raws","Tsundere%-Raws","%-VARYG","HorribleSubs","SubsPlus%+", "Yameii"})
profile-restore=copy
deband=yes

[short]
profile-cond=duration <= 60
profile-restore=copy
loop-file=inf

[youtube]
profile-cond=path:match("youtu%.?be") ~= nil
profile-restore=copy
slang=en,eng,enUS,en-US
sub-auto=fuzzy
ytdl-raw-options=cookies-from-browser=firefox,ignore-config=,write-sub=,write-auto-sub=,sub-lang="en.*"

# =================================================================================================
# Manual Profiles
# =================================================================================================

[hq]
profile=high-quality
deband=yes
#scale=ewa_lanczossharp

[standard]
profile=fast
deband=no
#scale=spline36   # or bilinear for maximum battery saving

[stereo]
audio-channels=stereo

[nostereo]
audio-channels=auto-safe
